###錯誤 :( 後台爆掉了！

OperationalError at /admin/note/note/10/change/
no such column: note_note002.detail
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/note/note/10/change/
Django Version:	2.2.6
Exception Type:	OperationalError
Exception Value:	
no such column: note_note002.detail
Exception Location:	/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 383
Python Executable:	/Users/chenmeijun/misdj/venv/bin/python
Python Version:	3.7.0
Python Path:	
['/Users/chenmeijun/misdj/misdj005',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf',
 '/Users/chenmeijun/misdj/venv/lib/python3.7/site-packages/odf']
Server time:	星期五, 11 十月 2019 05:50:31 +0000
# misdj-ww
